<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BillingFinance</name>
   <tag></tag>
   <elementGuidId>8ce53763-87a3-4872-a16e-11b57d89316f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//i[@class=&quot;am-BillingFinance&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//i[@class=&quot;am-BillingFinance&quot;]</value>
      <webElementGuid>6ce00dd3-d8c7-4933-80b7-2249e07c06db</webElementGuid>
   </webElementProperties>
</WebElementEntity>
