<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>evergentSKU</name>
   <tag></tag>
   <elementGuidId>bd86f22a-94ac-444d-b30b-f08b1153db44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//p[contains(@class,'MuiTypography-body2')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//p[contains(@class,'MuiTypography-body2')]</value>
      <webElementGuid>b71412a0-0c17-45f5-bd9b-507fa8b1d3c3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
