<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>shahidSportPrice</name>
   <tag></tag>
   <elementGuidId>8524eec7-b1e5-464f-bca3-93bd78a90b91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[contains(@class,'PackageSelectionUpgrade_price__')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(@class,'PackageSelectionUpgrade_price__')])[1]</value>
      <webElementGuid>67567e99-dbfb-426e-908a-d08b65ce6836</webElementGuid>
   </webElementProperties>
</WebElementEntity>
